# ----------------------------------------------
# Script Recorded by ANSYS Electronics Desktop Version 2021.1.0
# 15:11:30  Nov 27, 2023
# ----------------------------------------------
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_70um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_80um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_90um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_100um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_110um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_120um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_130um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_140um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_150um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_160um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_170um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_180um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_190um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_200um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_210um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_220um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_230um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_240um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_250um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_260um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_270um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_280um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_290um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_300um.aedt", True)
oProject = oDesktop.NewProject()
oProject.SaveAs("d:\\Andre\\paper_sweeps\\project_storage\\clt_sweep_3830um_310um.aedt", True)
